
server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:

        # Route 1 : Queue Service
        - id: queue-service
          uri: lb://queue-service
          predicates:
            - Path=/api/queues/**

        # Route 2 : Ticket Service
        - id: ticket-service
          uri: lb://ticket-service
          predicates:
            - Path=/api/tickets/**

        # Route 3 : User Service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        # Route 4 : Estimation Service
        - id: estimation-service
          uri: lb://estimation-service
          predicates:
            - Path=/api/estimations/**

        # Route 5 : Notification Service
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**

  # ---- Configuration Keycloak JWT ----
  security:
    oauth2:
      resourceserver:
        jwt:
          # URL du realm Keycloak ? il va télécharger automatiquement la clé publique
          # En local : http://localhost:8180/realms/waitless-realm
          # En Docker : http://keycloak:8080/realms/waitless-realm
          issuer-uri: http://localhost:8180/realms/waitless-realm

# ---- Eureka ----
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# ---- Actuator (Health Check) ----
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
